language: go
go:
  - 1.4
sudo: false
cache:
  directories:
    - /home/travis/gopath/
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
script:
  - go test -v ./...
after_success:
  - go get github.com/mitchellh/gox
  - gox -build-toolchain
  - go get github.com/tcnksm/ghr
  - gox -output "dist/{.OS}_{.Arch}_{.Dir}"
  - ghr --username tcnksm-sample --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/
